# Generated by Django 6.0.6 on 2026-06-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questsubmission',
            name='is_public',
        ),
    ]
