# Generated by Django 6.0.6 on 2026-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_questsubmission_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questsubmission',
            name='uploaded_proof',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='quest_submissions/'),
        ),
    ]
