# Generated by Django 6.0.7 on 2026-09-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_questsubmission_uploaded_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questsubmission',
            name='uploaded_proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
